version: "3.9"

services:
  flask-kube-app:
    build: .
    container_name: flask-kube-app
    image: flask-kube-app:latest
    restart: always
    ports:
      - "80:5000"
    volumes:
      - .:/src
    networks:
      - flask-kube-app-net

networks:
  flask-kube-app-net:
    driver: bridge