apiVersion: v1
kind: Service
metadata:
  name: flask-kube-app-service
spec:
  type: NodePort
  selector:
    app: flask-kube-app-label
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000